### ISSUE TITLE
estep validator error

### ISSUE THREAD

**Issue by arnikz** [NLeSC/software.esciencecenter.nl#78]
I'm getting the following error on my MacBook (OS X 10.11.2; Python 2.7.1):
Is this due to my *.md files or something else? Thanks.

$ estep validate -v
Traceback (most recent call last):
  File "/usr/local/bin/estep", line 9, in <module>
    load_entry_point('estep==1.0.0', 'console_scripts', 'estep')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 357, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2394, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2108, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/Users/arni/Downloads/mygitrepos/software.esciencecenter.nl/estep/script.py", line 23, in <module>
    from .validate import Validator, AbstractValidators, url_to_path, url_to_collection_name, load_schemas
  File "/Users/arni/Downloads/mygitrepos/software.esciencecenter.nl/estep/validate.py", line 88, in <module>
    class AbstractValidators(AbstractValidator, six.moves.UserList):
AttributeError: '_MovedItems' object has no attribute 'UserList'

**Comment by blootsvoets** [comment]
Try a
```
pip install -r requirements.txt
```
We got a previous one fixed because of a different `six` version.

**Comment by arnikz** [comment]
I got now the correct six version (1.10.0) but the error remains.

**Comment by jmaassen** [comment]
Same error for me on Linux Mint 17

**Comment by blootsvoets** [comment]
Hmm... ok. Maybe we'll add a part in the README that people have to use virtualenv or conda to install the requirements. e.g. (from repository directory):
```shell
cd ..
sudo pip install virtualenv
virtualenv estepenv
. estepenv/bin/activate
cd software.esciencecenter.nl
pip install -r requirements
pip install .
```
Does that work?

**Comment by sverhoeven** [comment]
For Jsaon, using a virtualenv worked.

**Comment by arnikz** [comment]
Thanks, works fine now. B.t.w. the last cmd line seems redundant.
