### ISSUE TITLE
estep validation error windows

### ISSUE THREAD

**Issue by sonjageorgievska** [NLeSC/software.esciencecenter.nl#87]
```
C:\Users\sonja\Documents\GitHub\software.esciencecenter.nl>estep validate -v
Locating local references
Collection: software
Traceback (most recent call last):
  File "C:\Users\sonja\Anaconda3\Scripts\estep-script.py", line 9, in <module>
    load_entry_point('estep', 'console_scripts', 'estep')()
  File "c:\users\sonja\documents\software.esciencecenter.nl\estep\script.py", li
ne 109, in main
    resolve_local=not arguments['--no-local-resolve'])
  File "c:\users\sonja\documents\software.esciencecenter.nl\estep\script.py", li
ne 74, in validate
    for docname, document in collection.documents():
  File "c:\users\sonja\documents\software.esciencecenter.nl\estep\script.py", li
ne 41, in documents
    return recurseDirectory(self.directory, self.name)
  File "c:\users\sonja\documents\software.esciencecenter.nl\estep\script.py", li
ne 119, in recurseDirectory
    obj.append((path, jekyllfile2object(path, schemaType=schemaType)))
  File "c:\users\sonja\documents\software.esciencecenter.nl\estep\format.py", li
ne 57, in jekyllfile2object
    obj = jekyll2object(f.read(), contentProperty)
  File "C:\Users\sonja\Anaconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1509: cha
racter maps to <undefined>
```

**Comment by blootsvoets** [comment]
@sonjageorgievska could you check if #112 resolves your issue?

Run
```
git fetch
git checkout fix_utf8_read
pip install -e .
estep validate -v
```
For good measure, add some Unicode characters in one of the files, e.g. copy the text on https://www.esciencecenter.nl/profile/maarten-van-meersbergen-msc to `_person/m.vanmeersbergen.md` to the description and save, and run `estep validate -v` again.

**Comment by blootsvoets** [comment]
Stale issue. Closing.
